style: refactor and enhance UI
Frezyx/talker pull request #131
Opened 2023-07-26 09:44 UTC by jnelle

### Thanks a lot for contributing!<br>

- Rename the `bacgroundColor` parameter to `backgroundColor`
- Add the `buttonDismissText` parameter
- Add the `dismissButton` parameter
- Add the `titleTextStyle` parameter
- Add the `messageTextStyle` parameter
- Modify the `color` property in the `Container` decoration
- Modify the `style` property in the `Text` widget for `title`
- Modify the `style` property in the `Text` widget for `message`
- Add an `onPressed` callback to the `TextButton` widget
- Modify the `child` property in the `TextButton` widget
- use paddingOf instead size this method will cause the given [context] to rebuild any time that the [MediaQueryData.padding] property of the ancestor [MediaQuery] changes

2023-07-26 11:49 UTC, jnelle commented
Should work now, please trigger the workflow again

2023-07-26 15:39 UTC, jnelle commented
Is there something missing for merging?

2023-07-27 06:56 UTC, Frezyx requested changes

2023-07-27 06:56 UTC, Frezyx commented on packages/talker_flutter/lib/src/ui/widgets/snackbar.dart
> +  final Widget? dismissButton;
Maybe it 's better to call this field **dismissButtonText** like **dismissButton**?

2023-07-27 07:06 UTC, Frezyx approved these changes
Great work, @jnelle 🚀 
Thanks a lot!

2023-07-27 07:06 UTC, merged