fix wasm compilation
Frezyx/talker pull request #310
Opened 2024-12-29 23:44 UTC by abdelaziz-mahdy

it should fix https://github.com/Frezyx/talker/issues/301, but i dont have a way to be 100 % sure, since it didnt fail to compile for me without it

2025-01-03 16:51 UTC, Frezyx requested changes

2025-01-03 16:51 UTC, Frezyx commented on packages/talker_flutter/lib/src/utils/run_talker_zoned_guarded/run_talker_zoned_guarded_native.dart
> +}
I think this code is same for io and web realizations
Can we separate only ``_setupErrorHooks`` method to avoid repeating ща the code?

2025-01-03 16:54 UTC, Frezyx commented
Hello @abdelaziz-mahdy !
Thank you for this contribution ❤️ 

Can you fix review issues before we merge this PR ?

2025-01-03 20:02 UTC, abdelaziz-mahdy commented on packages/talker_flutter/lib/src/utils/run_talker_zoned_guarded/run_talker_zoned_guarded_native.dart
> +}
i had to expose everything, so it can be used by the other files, i hope thats okay

i couldnt get it to work without exposing them

2025-01-04 03:18 UTC, Frezyx approved these changes

2025-01-04 05:16 UTC, merged